allow [ character in title
tldr-pages/tldr-lint pull request #44
Opened 2021-02-02 23:13 UTC by sbrl

In https://github.com/tldr-pages/tldr/pull/5205, a new page for `[` is being added. tldr-lint doesn't like that very much, so this (should) fix the issue.

2021-02-03 00:20 UTC, bl-ue commented
> tldr-lint doesn't like that very much

But at least it likes it a little tiny bit? 😄

2021-02-03 00:21 UTC, bl-ue approved these changes
It works!

2021-02-03 00:27 UTC, MasterOdin requested changes
You need to do `npm run jison` and commit the updated `lib/tldr-parser.js` file.

Might also behoove us to add a success test case with the page that was failing before making this change to prevent regressions.

2021-02-03 00:38 UTC, bl-ue commented
Why do we commit a generated file?

2021-02-03 08:30 UTC, owenvoke commented
Because the generated file is released with the npm release, as it's used by the parser. Otherwise Jison would have to be run on every machine the linter is installed on.

2021-02-03 08:31 UTC, owenvoke commented
I guess we also need to add this to the allowed filename characters (which is in one of the JS files)? As long as `[` is a supported character on all OSs.

2021-02-03 12:07 UTC, bl-ue commented
@owenvoke - `[` and `]` support on the major platforms:
- macOS - ✅ 
- Windows - ✅
- Linux - ✅

2021-02-12 21:42 UTC, sbrl commented
Oh, thanks! I'm completely inexperienced with contributing to the linter. I made this PR with the GH web interface :P

@owenvoke: I can't find the allowed filename characters bit. I found the end of tldr-lint, but that shouldn't present an issue with respect to filename.

2021-02-12 22:43 UTC, owenvoke commented
@sbrl, whoops. I'm being an idiot. I was thinking of this bit, no need to do anything. 👍🏻
https://github.com/tldr-pages/tldr-lint/blob/main/lib/tldr-lint.js#L196

Just triggered a re-run of the CI as one of them failed. But all looks good to me.

2021-02-12 22:43 UTC, owenvoke approved these changes

2021-02-14 15:58 UTC, bl-ue approved these changes

2021-02-14 15:59 UTC, merged